# Generated by Django 4.1.1 on 2022-11-30 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parma', '0017_alter_question_date_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Windows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontImgSrc', models.ImageField(upload_to='own-app/src/images')),
                ('backText', models.CharField(max_length=200)),
                ('state', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 30, 10, 17, 16, 731746), verbose_name='Дата публикации'),
        ),
    ]
