# Generated by Django 4.1.3 on 2022-12-01 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parma', '0019_alter_question_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 20, 35, 7, 230196), verbose_name='Дата публикации'),
        ),
    ]
